version: "3.8"
services:

  openresty:
    image: openresty/openresty:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx

networks:
  default:
    external:
      name: rp64-net
